// ux.symfony.com/assets/svelte/src/components/PackageList.svelte
<script lang='ts'>
    import { fade } from 'svelte/transition';
    import { flip } from 'svelte/animate';

    export let packages = [];
    let transitionDuration = 200;
</script>

{#if packages.length === 0}
    No packages found
{:else}
    <div class="PackageList">
        {#each packages as uxPackage(uxPackage.name)}
            <div class="PackageListItem"
                animate:flip={{duration: transitionDuration}} in:fade={{duration:transitionDuration}}
            >
                <div class="PackageListItem__icon" style="--gradient: {uxPackage.gradient};">
                    <img src="{uxPackage.imageUrl}" alt="Image for the {uxPackage.humanName} UX package" />
                </div>
                <h3 class="PackageListItem__label">
                    <a href="{uxPackage.url}">{uxPackage.humanName}</a>
                </h3>
            </div>
        {/each}
    </div>
{/if}

// ux.symfony.com/assets/react/src/components/PackageList.jsx
import React from 'react';

export default function (props) {
  if (props.packages.length === 0) {
    return 'No packages found';
  }

  return (
    <div className="PackageList">
      {props.packages.map(item => (
        <div className="PackageListItem" key={item.id}>
          <div className="PackageListItem__icon" style={{'--gradient': item.gradient}}>
            <img src={item.imageUrl} alt={`Image for the ${item.humanName} UX package`}/>
          </div>
          <h3 className="PackageListItem__label">
            <a href={item.url}>{item.humanName}</a>
          </h3>
        </div>
      ))}
    </div>
  );
}
