// ux.symfony.com/code_snippets/_PackageSearch.vue
<template>
    <div>
        <input v-model="search" />

        <div class="row">
            <a v-for="uxPackage in filteredPackages" :href="uxPackage.url">
                <img :src="uxPackage.imageUrl" />
                <h4>{{ uxPackage.humanName }}</h4>
            </a>
        </div>
    </div>
</template>

<script setup>
import { computed, ref } from 'vue';

const props = defineProps({
    packages: Array,
});

const search = ref('');

const filteredPackages = computed(() => {
    return props.packages.filter(
        uxPackage => uxPackage.humanName.includes(search.value)
    );
});
</script>

// ux.symfony.com/code_snippets/_PackageSearch.jsx
import React, { Component } from 'react';

export default class extends Component {
    constructor() {
      super();

      this.state = { search: '' };
    }

    render() {
        return (
            <div>
                <input
                    value={this.state.search}
                    onChange={(event) => this.setState({search: event.target.value})}
                />

                <div className="row">
                    {this.filteredPackages().map(item => (
                        <a key={item.name} href={item.url}>
                            <img src={item.imageUrl} />
                            <h4>{item.humanName}</h4>
                        </a>
                    ))}
                </div>
            </div>
        );
    }

    filteredPackages() {
        return this.props.packages.filter((uxPackage) => {
            return uxPackage.humanName.includes(this.state.search)
        });
    }
}
